headers = []
redirects = []

[functions]

[functions."*"]

[[plugins]]
origin = "ui"
package = "@netlify/plugin-lighthouse"
pinned_version = "6"

[plugins.inputs]

[build]
publish = "/Users/dan/code/oss/dans-blog/dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "bun run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]