%%{init: {
  'logLevel': 'debug',
  'theme': 'base',
  'gitGraph': {'mainBranchName': 'main', 'showBranches': 1},
  'themeVariables': {
    'gitBranchLabel0': '#ffffff',
    'gitBranchLabel1': '#ffffff',
    'gitBranchLabel2': '#ffffff',
    'gitBranchLabel3': '#ffffff',
    'gitBranchLabel4': '#ffffff',
    'gitBranchLabel5': '#ffffff',
    'tagLabelColor': '#333333',
    'tagLabelBackground': '#efefef',
    'tagLabelBorder': '#ffffff'
} } }%%

gitGraph TB:
  commit tag:"🏷️ v1.0.0" id: "abcdef"
  commit tag:"🏷️ v1.0.1" id: "bbcccd"

  branch feat/login-redirect
  commit id: "feat"
  checkout main

  branch fix/auth-router order: 3
  commit id: "fix"
  checkout main

  merge fix/auth-router id: "fix/auth-router ➡️"
  merge feat/login-redirect id: "feat/login-redirect ➡️" tag: "🏷️ v1.0.2"

  checkout main

