#!/usr/bin/env bun
/**
 * Generate a bullet outline per talk from its canonical 40-minute outline.
 *
 *   bun artifacts/speaking-portfolio-expanded/bullets.ts            all talks
 *   bun artifacts/speaking-portfolio-expanded/bullets.ts judgment   one talk
 *
 * Output: talks/<slug>/bullets.md — a one-screen spine plus, per
 * slide, the on-screen lines, the topic sentence of each spoken paragraph, and
 * the Story, Stage direction and Source lines. Rehearsal and CFP-form material;
 * the outline stays the single source. Never edit the generated files.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { TALKS, parseOutline, fmt, toSec } from './build-talk';

const root = dirname(new URL(import.meta.url).pathname);
const selected = process.argv.slice(2).filter(s => !s.startsWith('--'));
const slugs = selected.length ? selected : Object.keys(TALKS);

/** The bullet sheet sits beside its outline, so links pass through unchanged. */
const rel = (s: string) => s;
const write = (p: string, s: string) => {
  mkdirSync(dirname(p), { recursive: true });
  if (!existsSync(p) || readFileSync(p, 'utf8') !== s) writeFileSync(p, s);
};

/**
 * The claim a paragraph opens with. Takes whole sentences until there is enough
 * to stand alone, so a short opener keeps the sentence that completes it.
 */
const topicSentence = (para: string) => {
  const sentences = para.match(/[^.?!]+[.?!]+(?:\s|$)/g);
  if (!sentences) return para.trim();
  let text = '';
  for (const sentence of sentences) {
    text += sentence;
    if (text.trim().length >= 40) break;
  }
  return text.trim();
};

const bulletsFor = (slug: string) => {
  const talk = TALKS[slug];
  if (!talk) throw Error(`Unknown talk: ${slug}`);
  const { slides } = parseOutline(readFileSync(join(root, 'talks', slug, 'outline-40min.md'), 'utf8'));
  const minutes = toSec(slides[slides.length - 1].end) / 60;
  const lines: string[] = [];

  lines.push(`# ${talk.title.replace(/\.$/, '')}: bullet outline`, '');
  const blurb = talk.description.replace(new RegExp(`^${talk.title}:\\s*`), '');
  lines.push(blurb.charAt(0).toUpperCase() + blurb.slice(1), '');
  lines.push(
    `Generated from [the 40-minute outline](outline-40min.md) by \`bun artifacts/speaking-portfolio-expanded/bullets.ts\`. ` +
      `Edit the outline, not this file. ${slides.length} slides, ${minutes} minutes, no Q&A. ` +
      `Every Story line needs Dan's own record before delivery. ` +
      `Shorter routes: [15](adaptation-15min.md) · [30](adaptation-30min.md).`,
    '',
  );

  lines.push('## Spine', '');
  for (const s of slides) {
    const dur = (toSec(s.end) - toSec(s.start)) / 60;
    lines.push(`${s.n}. **${s.heading}** — ${s.start} · ${s.pacing} · ${fmt(dur)}`);
  }
  lines.push('');

  lines.push('## Slides', '');
  for (const s of slides) {
    const dur = (toSec(s.end) - toSec(s.start)) / 60;
    lines.push(`### ${s.n}. ${s.heading}`, '');
    lines.push(`${s.start}–${s.end} · ${s.pacing} · ${fmt(dur)}`, '');
    if (s.visible.length) lines.push(...s.visible.map(v => `> ${rel(v)}`), '');
    const beats = s.spoken.map(p => `- ${rel(topicSentence(p))}`);
    if (s.image) beats.push(`- Diagram — ${s.image.alt}`);
    if (s.table) beats.push(`- Table — ${s.table[0].join(' · ')}, ${s.table.length - 1} rows`);
    if (s.story) beats.push(`- Story — ${rel(s.story)}`);
    if (s.stage) beats.push(`- Do — ${rel(s.stage)}`);
    for (const src of s.sources) beats.push(`- Source — ${rel(src)}`);
    lines.push(...beats, '');
  }
  return lines.join('\n').trimEnd() + '\n';
};

for (const slug of slugs) {
  write(join(root, 'talks', slug, 'bullets.md'), bulletsFor(slug));
  console.log(`${slug}: bullet outline written`);
}

if (!selected.length) {
  const rows = Object.keys(TALKS)
    .map(slug => `| ${TALKS[slug].title} | [Bullets](${slug}/bullets.md) | [40-minute outline](${slug}/outline-40min.md) |`)
    .join('\n');
  write(
    join(root, 'talks', 'bullets-index.md'),
    `# Bullet outlines\n\nOne compressed sheet per talk: the spine in a screen, then each slide's on-screen lines, ` +
      `the topic sentence of every spoken paragraph, and its Story, delivery and source notes. Use them to rehearse the arc, ` +
      `to fill a CFP form's outline field, and to find the slide that owns an idea.\n\n` +
      `Generated by \`bun artifacts/speaking-portfolio-expanded/bullets.ts\`. The 40-minute outlines remain canonical; ` +
      `edits here are overwritten.\n\n| Talk | Bullet outline | Canonical source |\n| --- | --- | --- |\n${rows}\n`,
  );
  console.log('index written');
}
