import {chromium} from 'playwright';
import {parseQuiz} from '../../../../src/scripts/i18n/quiz-parser.ts';
const root = `${process.cwd()}/reports/i18n/quiz-review-2026-09-14/after`;
const rows = await Bun.file(`${root}/../selection.json`).json();
for (const row of rows) row.quiz = parseQuiz(await Bun.file(row.targetPath).text());
const browser=await chromium.launch();
const results=await Promise.all(rows.map(async r=>{const context=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'America/Denver',reducedMotion:'reduce'});const p=await context.newPage();const out={locale:r.locale,slug:r.slug,checks:[],errors:[]};p.on('pageerror',e=>out.errors.push(e.message));
const visit=async()=>{await p.goto(`http://localhost:4244/${r.locale}/${r.slug}/`,{timeout:120000,waitUntil:'domcontentloaded'});await p.locator('#qq-1').scrollIntoViewIfNeeded();await p.locator('.quiz-ui[data-quiz-logic-initialized="true"]').waitFor({timeout:60000});await p.waitForFunction(()=>!!document.querySelector('.quiz-ui.quiz-slides-active'),{timeout:60000});};
const goto=async i=>{await p.locator('.quiz-dot').nth(i).focus();await p.keyboard.press('Enter');await p.waitForTimeout(700);const q=p.locator(`#qq-${i+1}`);await q.scrollIntoViewIfNeeded();await p.waitForFunction(id=>!document.querySelector(id)?.closest('astro-island')?.hasAttribute('ssr'),`#qq-${i+1}`);return q;};
try{const t=Date.now();await visit();out.readyMs=Date.now()-t;out.lang=await p.locator('html').getAttribute('lang');out.dir=await p.locator('html').getAttribute('dir');
for(let i=0;i<r.quiz.challenges.length;i++){const q=await goto(i);const opts=q.locator('.option');const idx=r.quiz.challenges[i].options.findIndex(o=>o.isAnswer);const c={q:i+1,options:await opts.allTextContents()};out.checks.push(c);await q.locator('.toggle-explainer').click();await p.waitForTimeout(200);c.explanationLength=(await q.locator('.help-box').innerText()).trim().length;c.explanationOpened=await q.locator('.card-flip').count()===1;await q.locator('.toggle-explainer').click();await p.waitForTimeout(200);if(i===0){await opts.nth(idx===0?1:0).click();c.wrong=await q.getAttribute('data-question-correct');}await opts.nth(idx).focus();await p.keyboard.press(i%2?'Space':'Enter');await p.waitForTimeout(150);c.correct=await q.getAttribute('data-question-correct');await p.waitForTimeout(1100);}
out.correct=await p.locator('.challenge.correct').count();out.score=await p.locator('.quiz-score-bar-value').innerText();out.completed=await p.locator('.quiz-completion-card').isVisible();out.storage=await p.evaluate(()=>({...localStorage}));await visit();for(let i=0;i<r.quiz.challenges.length;i++)await goto(i);out.restored=await p.locator('.challenge.correct').count();
let q=await goto(1);await p.setViewportSize({width:390,height:844});await q.scrollIntoViewIfNeeded();await p.waitForTimeout(250);out.mobile=await p.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,dir:getComputedStyle(document.querySelector('.challenge')).direction,codeDir:getComputedStyle(document.querySelector('#qq-2 pre')||document.querySelector('#qq-2 code')).direction}));await p.screenshot({path:`${root}/${r.locale}-mobile.png`});await q.locator('.toggle-explainer').click();await p.waitForTimeout(300);await p.screenshot({path:`${root}/${r.locale}-explanation-mobile.png`});await q.locator('.toggle-explainer').click();await p.setViewportSize({width:1440,height:1000});await q.scrollIntoViewIfNeeded();await p.screenshot({path:`${root}/${r.locale}-desktop.png`});await p.locator('.quiz-reset-button').click();await p.waitForTimeout(1500);out.afterReset=await p.locator('.challenge.correct').count();
}catch(e){out.failure=String(e);await p.screenshot({path:`${root}/${r.locale}-failure.png`}).catch(()=>{});}console.log(JSON.stringify({locale:out.locale,readyMs:out.readyMs,correct:out.correct,score:out.score,restored:out.restored,reset:out.afterReset,mobile:out.mobile,failure:out.failure,errors:out.errors}));await Bun.write(`${root}/${r.locale}-results.json`,JSON.stringify(out,null,2));await context.close();return out;}));await Bun.write(`${root}/final-browser-results.json`,JSON.stringify(results,null,2));await browser.close();

if (results.some((r, i) => r.failure || r.errors.length || r.correct !== rows[i].quiz.challenges.length
  || r.restored !== r.correct || r.afterReset !== 0 || r.mobile.codeDir !== 'ltr'
  || r.mobile.scrollWidth > r.mobile.width || !r.completed
  || r.checks.some(c => c.correct !== 'true' || !c.explanationOpened))) process.exitCode = 1;
